[build]
builder = "nixpacks"

[deploy]
startCommand = "python wsgi_server.py"

[build.nixpacks]
providers = ["python"]

[build.nixpacks.apt]
packages = [
    "libgobject-2.0-0",
    "libcairo2",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libgdk-pixbuf2.0-0",
    "libffi-dev",
    "shared-mime-info"
]