# Generated by Django 5.1.4 on 2025-10-03 22:01

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_coupon_storelocation_profile_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop the existing assigned_employee column to fix type mismatch
        migrations.RunSQL(
            "ALTER TABLE accounts_order DROP COLUMN IF EXISTS assigned_employee_id;",
            reverse_sql="-- No reverse operation needed"
        ),
        # Re-add the assigned_employee field with correct type
        migrations.AddField(
            model_name='order',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
