# Generated by Django 5.1.4 on 2025-09-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_dimensions_product_is_in_stock_and_more'),
    ]

    operations = [
    ]
