# Generated by Django 5.1.4 on 2025-10-03 22:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productcomparison_productrecommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode_value', models.CharField(db_index=True, max_length=50, unique=True)),
                ('barcode_type', models.CharField(choices=[('EAN13', 'EAN-13'), ('UPC', 'UPC'), ('CODE128', 'Code 128'), ('CUSTOM', 'Custom'), ('GENERATED', 'Auto-Generated')], default='GENERATED', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary barcode for this product')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this barcode', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.product')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
                'unique_together': {('product', 'barcode_value')},
            },
        ),
    ]
