# Generated by Django 5.0.6 on 2025-01-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('mart', 'Mart'), ('bar', 'Bar'), ('both', 'Both Mart & Bar')], default='mart', help_text='Which section this product belongs to', max_length=10),
        ),
    ]
