# Generated by Django 5.2.7 on 2025-10-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_merge_size_variant_migrations'),
        ('products', '0027_add_size_variant_fields_safe'),
    ]

    operations = [
    ]
